#!/usr/bin/perl
use strict;

# This is part of modern Perl distributions.
use FindBin;
use lib "$FindBin::Bin";
use File::Copy;
use File::Basename;

# Used to process the google search requests.
use LWP::Simple qw(get);
use URI::URL;
use HTML::Parser;

# This is a module that requires installation.
# See requirements in README file to install google search
use Google::Search;

# These are part of modern Perl distributions.
use Getopt::Long;

# These modules aren't necessarily "standard" with Perl.  You might need to
# install them seperately.
use Digest::SHA1 qw(sha1);
use LWP::UserAgent;

# This is part of TorrentSniff, and should have been distributed with it.
use BitTorrent::BDecode;

my $VERSION = '0.1';
my $PROGRAM_NAME = 'TorrentCheque';
my $TORRENT_HASH;

main();
exit 0;

sub main {
 	# Autoflush stdout so messages to stderr will stick with the associated
        # stdout messages.
        local $| = 1;

	my $opt_torrent_directory;
	my $opt_help = 0;
	my $opt_search;

	 GetOptions (
                'd|torrent-directory!' => \$opt_torrent_directory,
                'h|?|help' => \$opt_help,
		'g|search!' => \$opt_search,
                ) or usage_exit();

	if($opt_help) {
        	usage_exit();
        }

	my ($directory) = (1) ;
	if($opt_torrent_directory) {
		$directory || 0;
	}

	if($directory == 0) {
                print STDERR "No torrent directory requested.\n";
                usage_exit();
        }

	# Called if -g (google search) switch is used. Issue a google search instead of processing torrent files
	if($opt_search) {
		my $word;
		$word = $ARGV[0];
                google_search($word);
                exit 0;
	}

	if(not @ARGV) {
                usage_exit();
        }
	
	foreach my $arg (@ARGV) {
                if($arg =~ m|://|) {
			#http url torrent processing
		} else {
			process_dir($arg, $directory);
			#REMOVE IF YOU DONT WANT TO SEARCH GOOGLE
			google_search($TORRENT_HASH);
		}
	}
}

sub process_dir {
	my $ua = LWP::UserAgent->new;
	$ua->agent($PROGRAM_NAME . "/" . $VERSION);

	my($file, $directory) = @_;	
	local *TOR;
	if( not open(TOR, "<", $file) ) {
                print STDERR "Unable to read $file because of $!\n";
                return 0;
        }
	binmode(TOR);
	my $body;
	read(TOR, $body, (-s $file));
        close(TOR);
        output_torrent_data($body, $directory, $file);
}

sub output_torrent_data {
        my($body, $directory, $file) = @_;
        my $result = process_torrent_data($body);
        if(not defined $result) {
                print STDERR "Problem reading torrent file\n";
        }

        if($directory) {
                #print  "$result->{'hash'}\n";
		# 1. Identify .torrent hash, lookup hash against fenopy.eu's api
		fenopy_api("$result->{'hash'}",$file);
        }
}

sub process_torrent_data {
        my($body) = @_;
        my %result;
        my $t = BitTorrent::BDecode::bdecode(\$body);
        my $info = $t->{'info'};
        my $s = substr($body, $t->{'_info_start'}, $t->{'_info_length'});
        my $hash = bin2hex(sha1($s));
        my $announce = $t->{'announce'};

        $result{'hash'} = $hash;
        $result{'announce'} = $announce;
        $result{'files'} = [];
        my $tsize = 0;
        if(defined($info->{'files'})) {
                foreach my $f (@{$info->{'files'}}) {
                        my %file_record = ( 'size' => $f->{'length'});

                        $tsize += $f->{'length'};
                        my $path = $f->{'path'};

                        if(ref($path) eq 'ARRAY') {
                                $file_record{'name'} = $info->{'name'}.'/'.$path->[0];
                        } else {
                                $file_record{'name'} = $info->{'name'}.'/'.$path;
                        }
                        push @{$result{'files'}}, \%file_record;

                }
        } else {
                $tsize += $info->{'length'},

		push @{$result{'files'}},
                        {
                                'size' => $info->{'length'},
                                'name' => $info->{'name'},
                        };
        }
        $result{'total_size'} = $tsize;

        return \%result;
}

# Add commas to number
sub commify {
	local $_ = shift;
	1 while s/^([-+]?\d+)(\d{3})/$1,$2/;
	return $_;
}

# Encode binary as hex characters
sub bin2hex {
	my ($d) = @_;
	$d =~ s/(.)/sprintf("%02x",ord($1))/egs;
	$d = lc($d);
	return $d;
}

#query fenopy using the torrents hash and remove the file from the torrent directory if not verified
sub fenopy_api {
	my ($hash, $file) = @_;
        my $req = HTTP::Request->new(POST => "http://fenopy.eu/fakefinder/api.php?hash=$hash");
        $req->content_type('application/x-www-form-urlencoded');
        $req->content('query=libwww-perl&mode=dist');
        #Pass request to the user agent and get a response back
	my $ua;
	if(not defined $ua) {
                $ua = LWP::UserAgent->new(
                        'env_proxy' => 1,
                        'agent'          => "$PROGRAM_NAME/$VERSION ",
                        'timeout'        => 15,
                );
	}
        my $res = $ua->request($req);
        # Check the outcome of the response
        if ($res->is_success)
        {
		if ($res->content eq "verified")
                {
                	#do something with verified files
			print $res->content, " : $hash\n\n" ;
			$TORRENT_HASH = $hash;
                } else {
                        #remove file
			unlink ($file) or die $!;
			print $res->content, " : $hash DELETED!\n" ;
                }
        }  else {
		print "Status: Failed to resolve using fenopy.eu's api!\n";
        }
}

sub google_search {
	# initiate google search and input our give variable keyword which is $word
	my ($word) = @_;
	my $search = Google::Search->Web( query => $word );
	while ( my $result = $search->next ) { # this will search first 50 results
		# this will output our google search results back to console.
		print $result->rank, " - ", $result->uri, "\n";
		my $url = $result->uri;
		process_webresults ("$url");
	} #while
} #search



sub process_webresults {
	my ($url) = @_;
	#process each web URL for search terms
	#print "$url\n";
	my $html = 0;
	$html = get($url);
	my @lines;
	my $parser = new MyParser;
	$parser->parse("$html");
}


#Base class Parser to convert each torrent link to plain text
{
    package MyParser;
    use base qw(HTML::Parser);

    # this method supplies the text, no tags :)
    #TODO: get predefined regex expressions to search for
    sub text {
        my ($self, $origtext) = @_;
        #print $origtext, "\n";
	my $fake_count =0;
	if ($origtext =~ m/fake|FAKE/g) {
		$fake_count++;
	} 
	if ($fake_count != 0) {
		print "Fake comments found: $fake_count\n";
	} else {
		
	}
    }
}

